config/routes.rb
Rails.application.routes.draw do
  get 'roduction_houses/index'

  get 'roduction_houses/new'

  get 'roduction_houses/create'

  get 'roduction_houses/update'

  get 'roduction_houses/destroy'

  get 'roduction_houses/edit'

  get 'roduction_houses/show'

  resources :categories
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorie.rb
class Categorie < ApplicationRecord
    belongs_to :product
    has_many :variations, dependent: :destroy
    accepts_nested_attributes_for :variations
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :categories, dependent: :destroy
    has_one :production_house
    accepts_nested_attributes_for :production_house

    validates_associated :categories


end

app/models/production_house.rb
class ProductionHouse < ApplicationRecord
    belongs_to :product
end

app/models/variation.rb
class Variation < ApplicationRecord
    belongs_to :categorie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Categorie.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Categorie.new
    test = @category.variations.build
    
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Categorie.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categorie was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categorie was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categorie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Categorie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      puts params.inspect
      params.require(:categorie).permit(:material, :color,
       variations_attributes: [ :color, :material ])
     
    end
end

app/controllers/production_houses_controller.rb
class RoductionHousesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new 
    @product.build_production_house
  end

  # GET /products/1/edit
  def edit
    @product.build_production_house if @product.nutrition_fact.nil?    
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      byebug
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, 
      production_house_attributes: [ :name, :address ])
      
    end
end

app/controllers/roduction_houses_controller.rb
class RoductionHousesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roduction_houses_helper.rb
module RoductionHousesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material, id: :category_material %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :category_color %>
  </div>

  <%= form.fields_for :variation do |f| %>
    
  <div class="field">
   V color: <%= f.label :color %>
    <%= f.text_field :color, id: :variation_color %>
  </div>

  <div class="field">
   V material: <%= f.label :material %>
    <%= f.text_field :material, id: :variation_material %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  <% end %>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Material</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.material %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Material:</strong>
  <%= @category.material %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stores</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product, url: { action: "create" } do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <%= form.fields_for :production_house do |f| %>
    
  <div class="field">
   Product House: <%= f.label :name %>
    <%= f.text_field :name, id: :product_price %>
  </div>

  <div class="field">
   Product House: <%= f.label :address %>
    <%= f.text_field :address, id: :product_price %>
  </div>

  <% end %>




  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>ProductHouse name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/roduction_houses/create.html.erb
<h1>RoductionHouses#create</h1>
<p>Find me in app/views/roduction_houses/create.html.erb</p>

app/views/roduction_houses/destroy.html.erb
<h1>RoductionHouses#destroy</h1>
<p>Find me in app/views/roduction_houses/destroy.html.erb</p>

app/views/roduction_houses/edit.html.erb
<h1>RoductionHouses#edit</h1>
<p>Find me in app/views/roduction_houses/edit.html.erb</p>

app/views/roduction_houses/index.html.erb
<h1>RoductionHouses#index</h1>
<p>Find me in app/views/roduction_houses/index.html.erb</p>

app/views/roduction_houses/new.html.erb
<h1>RoductionHouses#new</h1>
<p>Find me in app/views/roduction_houses/new.html.erb</p>

app/views/roduction_houses/show.html.erb
<h1>RoductionHouses#show</h1>
<p>Find me in app/views/roduction_houses/show.html.erb</p>

app/views/roduction_houses/update.html.erb
<h1>RoductionHouses#update</h1>
<p>Find me in app/views/roduction_houses/update.html.erb</p>